/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef COMMANDS_H_
#define COMMANDS_H_

#define WM_SUCCESS 0

#define NCP_WLAN   0x00000000
#define NCP_BLE    0x10000000

#define NCP_TYPE_COMMAND		 0x00010000
#define NCP_TYPE_EVENT			 0x00020000
#define NCP_TYPE_RESPONSE		 0x00030000
#define NCP_CMD_WLAN_ASYNC_EVENT 0x00f00000

#define NCP_CMD_WLAN_STA       	0x00000000
#define NCP_CMD_WLAN_BASIC     	0x00100000
#define NCP_CMD_WLAN_NETWORK    0x00700000
#define NCP_CMD_WLAN_SOCKET     0x00900000

#define NCP_CMD_RESULT_OK 0x0000
#define NCP_CMD_RESULT_ERROR 0x0001
#define NCP_CMD_RESULT_NOT_SUPPORT 0x0002
#define NCP_CMD_RESULT_PENDING 0x0003
#define NCP_CMD_RESULT_BUSY 0x0004
#define NCP_CMD_RESULT_PARTIAL_DATA 0x0005
#define NCP_CMD_RESULT_INVALID_INDEX 0x0006

// WIFI --------------------------------------------------------------------------------------------
#define NCP_WLAN_SCAN_SEND	 		(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_COMMAND | 0x00000001)
#define NCP_WLAN_SCAN_RESPONSE 		(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_RESPONSE | 0x00000001)

#define NCP_WLAN_ADD_SEND    		(NCP_WLAN | NCP_CMD_WLAN_NETWORK | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_WLAN_ADD_RESPONSE    	(NCP_WLAN | NCP_CMD_WLAN_NETWORK | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_WLAN_REMOVE_SEMD 		(NCP_WLAN | NCP_CMD_WLAN_NETWORK | NCP_TYPE_COMMAND | 0x00000009)
#define NCP_WLAN_REMOVE_RESPONSE 	(NCP_WLAN | NCP_CMD_WLAN_NETWORK | NCP_TYPE_RESPONSE | 0x00000009)

#define NCP_CMD_WLAN_CONNECT 		(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_COMMAND | 0x00000002)
#define NCP_RSP_WLAN_CONNECT		(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_RESPONSE |0x00000002)

#define NCP_CMD_WLAN_DISCONNECT 	(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_RSP_WLAN_DISCONNECT 	(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_CMD_WLAN_VERSION   		(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_COMMAND | 0x00000004)
#define NCP_RSP_WLAN_VERSION   		(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_RESPONSE | 0x00000004)

#define NCP_CMD_WLAN_STAT  			(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_COMMAND | 0x00000007)
#define NCP_RSP_WLAN_STAT  			(NCP_WLAN | NCP_CMD_WLAN_STA | NCP_TYPE_RESPONSE | 0x00000007)

#define NCP_CMD_WLAN_NETWORK_INFO   (NCP_WLAN | NCP_CMD_WLAN_NETWORK | NCP_TYPE_COMMAND | 0x00000001)
#define NCP_RSP_WLAN_NETWORK_INFO   (NCP_WLAN | NCP_CMD_WLAN_NETWORK | NCP_TYPE_RESPONSE | 0x00000001)

#define NCP_CMD_SOCKET_OPEN    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000001)
#define NCP_RSP_SOCKET_OPEN    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000001)

#define NCP_CMD_SOCKET_CON     		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000002)
#define NCP_RSP_SOCKET_CON     		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000002)

#define NCP_CMD_SOCKET_RECV    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_RSP_SOCKET_RECV    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_CMD_SOCKET_SEND    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000004)
#define NCP_RSP_SOCKET_SEND    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000004)

#define NCP_CMD_SOCKET_SENDTO  		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000005)
#define NCP_RSP_SOCKET_SENDTO  		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000005)

#define NCP_CMD_SOCKET_BIND    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000006)
#define NCP_RSP_SOCKET_BIND    		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000006)

#define NCP_CMD_SOCKET_LISTEN  		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000007)
#define NCP_RSP_SOCKET_LISTEN  		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000007)

#define NCP_CMD_SOCKET_ACCEPT  		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000008)
#define NCP_RSP_SOCKET_ACCEPT  		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000008)

#define NCP_CMD_SOCKET_CLOSE   		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x00000009)
#define NCP_RSP_SOCKET_CLOSE   		(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x00000009)

#define NCP_CMD_SOCKET_RECVFROM 	(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_COMMAND | 0x0000000a)
#define NCP_RSP_SOCKET_RECVFROM 	(NCP_WLAN | NCP_CMD_WLAN_SOCKET | NCP_TYPE_RESPONSE | 0x0000000a)

// UAP -------------------------------------------------------------------
#define NCP_CMD_WLAN_BASIC_WLAN_RESET           (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_COMMAND | 0x00000001)
#define NCP_RSP_WLAN_BASIC_WLAN_RESET           (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_RESPONSE | 0x00000001)

#define NCP_CMD_WLAN_BASIC_WLAN_UAP_PROV_START  (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_COMMAND | 0x00000002)
#define NCP_RSP_WLAN_BASIC_WLAN_UAP_PROV_START  (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_RESPONSE | 0x00000002)

#define NCP_CMD_WLAN_BASIC_WLAN_UAP_PROV_RESET  (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_RSP_WLAN_BASIC_WLAN_UAP_PROV_RESET  (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_CMD_WLAN_BASIC_WLAN_UAP_PROV_SET_UAPCFG  (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_COMMAND | 0x00000004)
#define NCP_RSP_WLAN_BASIC_WLAN_UAP_PROV_SET_UAPCFG  (NCP_WLAN | NCP_CMD_WLAN_BASIC | NCP_TYPE_RESPONSE | 0x00000004)
// -----------------------------------------------------------------------

// Events ----------------------------------------------------------------
#define NCP_EVENT_MDNS_QUERY_RESULT   (NCP_WLAN | NCP_CMD_WLAN_ASYNC_EVENT | NCP_TYPE_EVENT | 0x00000003)

#define NCP_EVENT_MDNS_RESOLVE_DOMAIN (NCP_WLAN | NCP_CMD_WLAN_ASYNC_EVENT | NCP_TYPE_EVENT | 0x00000004)

#define NCP_EVENT_CSI_DATA            (NCP_WLAN | NCP_CMD_WLAN_ASYNC_EVENT | NCP_TYPE_EVENT | 0x00000005)

#define NCP_EVENT_WLAN_STA_CONNECT    (NCP_WLAN | NCP_CMD_WLAN_ASYNC_EVENT | NCP_TYPE_EVENT | 0x00000006)

#define NCP_EVENT_WLAN_STA_DISCONNECT (NCP_WLAN | NCP_CMD_WLAN_ASYNC_EVENT | NCP_TYPE_EVENT | 0x00000007)

#define NCP_EVENT_WLAN_STOP_NETWORK   (NCP_WLAN | NCP_CMD_WLAN_ASYNC_EVENT | NCP_TYPE_EVENT | 0x00000008)
// -----------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------

// BLE ---------------------------------------------------------------------------------------------
#define NCP_CMD_BLE_CORE         0x00000000
#define NCP_CMD_BLE_GAP          0x00100000
#define NCP_CMD_BLE_GATT         0x00200000
#define NCP_CMD_BLE_L2CAP        0x00300000
#define NCP_CMD_BLE_POWERMGMT    0x00400000
#define NCP_CMD_BLE_VENDOR       0x00500000
#define NCP_CMD_BLE_OTHER        0x00600000
#define NCP_CMD_BLE_EVENT        0x00f00000

#define NCP_BLE_MTU                 1024

#define NCP_CMD_BLE_GAP_SET_ADV_DATA         (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000001e)
#define NCP_RSP_BLE_GAP_SET_ADV_DATA         (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000001e)

#define NCP_CMD_BLE_GAP_START_ADV            (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000000a)
#define NCP_RSP_BLE_GAP_START_ADV            (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000000a)

#define NCP_CMD_BLE_GAP_STOP_ADV             (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000000b)
#define NCP_RSP_BLE_GAP_STOP_ADV             (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000000b)

#define NCP_CMD_BLE_GAP_START_SCAN           (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000000c)
#define NCP_RSP_BLE_GAP_START_SCAN           (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000000c)

#define NCP_CMD_BLE_GAP_STOP_SCAN            (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000000d)
#define NCP_RSP_BLE_GAP_STOP_SCAN            (NCP_BLE | NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000000d)
// -------------------------------------------------------------------------------------------------
/** NCP Command/Response definitions */
/** Bluetooth LE invalid command ID */
#define NCP_CMD_BLE_INVALID_CMD              (NCP_BLE| NCP_CMD_BLE_CORE | NCP_TYPE_COMMAND | 0x0000000a)
#define NCP_RSP_BLE_CORE_SUPPORT_CMD         (NCP_BLE| NCP_CMD_BLE_CORE | NCP_TYPE_RESPONSE | 0x00000001)

#define NCP_CMD_BLE_GAP_SET_DATA_LEN         (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x00000020)
#define NCP_RSP_BLE_GAP_SET_DATA_LEN         (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x00000020)

#define NCP_CMD_BLE_GAP_SET_PHY              (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000001f)
#define NCP_RSP_BLE_GAP_SET_PHY              (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000001f)

#define NCP_CMD_BLE_GAP_SET_SCAN_PARAM       (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000001d)
#define NCP_RSP_BLE_GAP_SET_SCAN_PARAM       (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000001d)

#define NCP_CMD_BLE_GAP_CONNECT              (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000000e)
#define NCP_RSP_BLE_GAP_CONNECT              (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000000e)

#define NCP_CMD_BLE_GAP_DISCONNECT           (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000000f)
#define NCP_RSP_BLE_GAP_DISCONNECT           (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000000f)

#define NCP_CMD_BLE_GAP_CONN_PARAM_UPDATE    (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x00000016)
#define NCP_RSP_BLE_GAP_CONN_PARAM_UPDATE    (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x00000016)

#define NCP_CMD_BLE_GAP_SET_FILTER_LIST      (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x0000001c)
#define NCP_RSP_BLE_GAP_SET_FILTER_LIST      (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x0000001c)

#define NCP_CMD_BLE_GAP_PAIR                 (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_COMMAND | 0x00000011)
#define NCP_RSP_BLE_GAP_PAIR                 (NCP_BLE| NCP_CMD_BLE_GAP | NCP_TYPE_RESPONSE | 0x00000011)


#define NCP_CMD_BLE_HOST_SERVICE_ADD         (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | 0x00000002)
#define NCP_RSP_BLE_HOST_SERVICE_ADD         (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | 0x00000002)

#define NCP_CMD_BLE_HOST_SERVICE_DISC        (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_RSP_BLE_HOST_SERVICE_DISC        (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_CMD_BLE_GATT_SET_VALUE           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | 0x00000006)
#define NCP_RSP_BLE_GATT_SET_VALUE           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | 0x00000006)

#define NCP_CMD_BLE_GATT_START_SERVICE       (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | 0x00000007)
#define NCP_RSP_BLE_GATT_START_SERVICE       (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | 0x00000007)

#define NCP_CMD_BLE_GATT_DISC_PRIM           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | GATT_DISC_PRIM_UUID)
#define NCP_RSP_BLE_GATT_DISC_PRIM           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | GATT_DISC_PRIM_UUID)

#define NCP_CMD_BLE_GATT_DISC_CHRC           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | GATT_DISC_CHRC_UUID)
#define NCP_RSP_BLE_GATT_DISC_CHRC           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | GATT_DISC_CHRC_UUID)

#define NCP_CMD_BLE_GATT_READ                (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | 0x00000011)
#define NCP_RSP_BLE_GATT_READ                (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | 0x00000011)

#define NCP_CMD_BLE_GATT_CFG_NOTIFY          (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | GATT_CFG_NOTIFY)
#define NCP_RSP_BLE_GATT_CFG_NOTIFY          (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | GATT_CFG_NOTIFY)

#define NCP_CMD_BLE_GATT_CFG_INDICATE        (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | GATT_CFG_INDICATE)
#define NCP_RSP_BLE_GATT_CFG_INDICATE        (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | GATT_CFG_INDICATE)

#define NCP_CMD_BLE_GATT_WRITE               (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | GATT_WRITE)
#define NCP_RSP_BLE_GATT_WRITE               (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | GATT_WRITE)

#define NCP_CMD_BLE_GATT_REGISTER_SERVICE    (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | 0x00000020)
#define NCP_RSP_BLE_GATT_REGISTER_SERVICE    (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | 0x00000020)

#define NCP_CMD_BLE_GATT_DESC_CHRC           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_COMMAND | GATT_DISC_DESC_UUID)
#define NCP_RSP_BLE_GATT_DESC_CHRC           (NCP_BLE| NCP_CMD_BLE_GATT | NCP_TYPE_RESPONSE | GATT_DISC_DESC_UUID)


#define NCP_CMD_BLE_L2CAP_CONNECT            (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_COMMAND | 0x00000002)
#define NCP_RSP_BLE_L2CAP_CONNECT            (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_RESPONSE | 0x00000002)

#define NCP_CMD_BLE_L2CAP_DISCONNECT         (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_RSP_BLE_L2CAP_DISCONNECT         (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_CMD_BLE_L2CAP_SEND               (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_COMMAND | 0x00000004)
#define NCP_RSP_BLE_L2CAP_SEND               (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_RESPONSE | 0x00000004)

#define NCP_CMD_BLE_L2CAP_REGISTER           (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_COMMAND | 0x0000000a)
#define NCP_RSP_BLE_L2CAP_REGISTER           (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_RESPONSE | 0x0000000a)

#define NCP_CMD_BLE_L2CAP_METRICS            (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_COMMAND | 0x0000000b)
#define NCP_RSP_BLE_L2CAP_METRICS            (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_RESPONSE | 0x0000000b)

#define NCP_CMD_BLE_L2CAP_RECEIVE            (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_COMMAND | 0x0000000c)
#define NCP_RSP_BLE_L2CAP_RECEIVE            (NCP_BLE| NCP_CMD_BLE_L2CAP | NCP_TYPE_RESPONSE | 0x0000000c)


#define NCP_CMD_BLE_VENDOR_POWER_MODE        (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_COMMAND | 0x00000001)
#define NCP_RSP_BLE_VENDOR_POWER_MODE        (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_RESPONSE | 0x00000001)

#define NCP_CMD_BLE_VENDOR_SET_UART_BR       (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_COMMAND | 0x00000002)
#define NCP_RSP_BLE_VENDOR_SET_UART_BR       (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_RESPONSE | 0x00000002)

#define NCP_CMD_BLE_VENDOR_SET_DEVICE_ADDR   (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_COMMAND | 0x00000003)
#define NCP_RSP_BLE_VENDOR_SET_DEVICE_ADDR   (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_RESPONSE | 0x00000003)

#define NCP_CMD_BLE_VENDOR_SET_DEVICE_NAME   (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_COMMAND | 0x00000004)
#define NCP_RSP_BLE_VENDOR_SET_DEVICE_NAME   (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_RESPONSE | 0x00000004)

#define NCP_CMD_BLE_VENDOR_CFG_MULTI_ADV     (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_COMMAND | 0x00000005)
#define NCP_RSP_BLE_VENDOR_CFG_MULTI_ADV     (NCP_BLE| NCP_CMD_BLE_VENDOR | NCP_TYPE_RESPONSE | 0x00000005)


#define NCP_EVENT_IUT_READY                  (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | CORE_EV_IUT_READY)

#define NCP_EVENT_ADV_REPORT                 (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_DEVICE_FOUND)

#define NCP_EVENT_DEVICE_CONNECTED           (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_DEVICE_CONNECTED)

#define NCP_EVENT_DEVICE_DISCONNECT          (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_DEVICE_DISCONNECTED)

#define NCP_EVENT_PASSKEY_DISPLAY            (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_PASSKEY_DISPLAY)

#define NCP_EVENT_IDENTITY_RESOLVED          (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_IDENTITY_RESOLVED)

#define NCP_EVENT_CONN_PARAM_UPDATE          (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_CONN_PARAM_UPDATE)

#define NCP_EVENT_SEC_LEVEL_CHANGED          (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_SEC_LEVEL_CHANGED)

#define NCP_EVENT_PAIRING_FAILED             (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_PAIRING_FAILED)

#define NCP_EVENT_BOND_LOST                  (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_BOND_LOST)

#define NCP_EVENT_PHY_UPDATED                (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_PHY_UPDATED)

#define NCP_EVENT_DATA_LEN_UPDATED           (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GAP_EV_DATA_LEN_UPDATED)

#define NCP_EVENT_GATT_NOTIFICATION          (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GATT_EV_NOTIFICATION | 0x200)

#define NCP_EVENT_ATTR_VALUE_CHANGED         (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GATT_EV_ATTR_VALUE_CHANGED | 0x200)

#define NCP_EVENT_GATT_CCC_CFG_CHANGED       (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GATT_EV_CCC_CFG_CHANGED | 0x200)

#define NCP_EVENT_GATT_SUBSCRIPTION        	 (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | GATT_EV_SUBSCRIPTION | 0x200)

#define NCP_EVENT_GATT_DISC_PRIM             (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | 0x19 | 0x200)

#define NCP_EVENT_GATT_DISC_CHRC             (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | 0x20 | 0x200)

#define NCP_EVENT_GATT_DISC_DESC             (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | 0x21 | 0x200)

#define NCP_EVENT_GATT_NCS_INFO              (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | 0x30 | 0x200)


#define NCP_EVENT_L2CAP_CONNECT              (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | L2CAP_EV_CONNECT | 0x300)

#define NCP_EVENT_L2CAP_DISCONNECT           (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | L2CAP_EV_DISCONNECT | 0x300)

#define NCP_EVENT_L2CAP_RECEIVE              (NCP_BLE| NCP_CMD_BLE_EVENT | NCP_TYPE_EVENT | L2CAP_EV_RECEIVE | 0x300)
// -------------------------------------------------------------------------------------------------

#endif /* COMMANDS_H_ */
